config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "venues#index"
  get "profile", to: "pages#profile", as: :profile

  resources :venues do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[create]
  end

  resources :reviews, only: %i[destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>
<% if error %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= error %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/alexagodzilla/venues-pay-and-play" class="icons"><i class="fab fa-github"></i></a>
    <a href="#" class="icons"><i class="fab fa-instagram"></i></a>
    <a href="#" class="icons"><i class="fab fa-twitter"></i></a>
    <a href="#" class="icons"><i class="fab fa-facebook"></i></a>
    <a href="#">Sitemap</a>
    <a href="#">Privacy</a>
    <a href="#"><i class="fa-solid fa-globe"></i> English (UK)</a>
    <a href="#"><i class="fa-solid fa-sterling-sign"></i> GBP</a>
  </div>
  <div class="footer-copyright">
    Pay and Play <i class="fas fa-heart"></i> © 2023 PnP, Inc.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand", style: "width: 50%" do %>
      <%= image_tag "pnp-white.png", style: "height: 35%; width: 35%" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My profile", profile_path, class: "nav-link me-3 text-white" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag(current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% else %>
              <%= image_tag("https://m.media-amazon.com/images/I/61NI-WmEbDL.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Bookings", profile_path, class: "dropdown-item" %>
              <%= link_to "Add your venue", new_venue_path, class: "dropdown-item" %>
              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-white"%>
          </li>
            <li class="nav-item">
            <%= link_to "Add your venue", new_venue_path, class: "nav-link text-white"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>