config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "venues#index"
  get "profile", to: "pages#profile", as: :profile

  resources :venues do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[create]
  end

  resources :reviews, only: %i[destroy]
end

app/views/pages/profile.html.erb
<div class="container booking-container">
  <div class="row mt-5">
    <div>
      <h3 class="mb-0 welcome-back">Welcome back, <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>!</h3>
    </div>
    <% if current_user.venues.any? %>
      <h2>My venues</h2>
      <% @venues.each do |venue| %>
        <div class="row my-5">
          <div class="card">
            <%= link_to venue_path(venue) do %>
              <% if venue.photo.attached? %>
                <%= cl_image_tag(venue.photo.key, crop: :thumb, gravity: :face, radius: 5) %>
              <% else %>
                <%= image_tag(venue.pic_url, crop: :thumb, gravity: :face, radius: 5) %>
              <% end %>
            <% end %>
            <div class="card-body .d-flex flex-column">
              <h5 class="card-title"><strong><%= link_to venue.name, venue_path(venue.id), class: "text-dark" %></strong></h5>
              <p class="card-text"><%= venue.location %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

  <h2 class="booking-header">Future bookings</h2>
    <% @future_bookings.each do |booking| %>
      <% venue = booking.venue %>
      <div class="row my-3">
        <div class="card">
          <%= link_to venue_path(venue) do %>
            <% if booking.venue.photo.attached? %>
              <%= cl_image_tag(booking.venue.photo.key, crop: :thumb, gravity: :face, radius: 5) %>
            <% else %>
              <%= image_tag(booking.venue.pic_url, crop: :thumb, gravity: :face, radius: 5) %>
            <% end %>
          <% end %>
          <div class="card-body flex-column">
            <h5 class="card-title"><strong><%= link_to venue.name, booking_path(booking), class: "text-dark" %></strong></h5>
            <p class="card-text card-location"><%= venue.location %></p>
            <p class="card-text bolder-font"><%= booking.start_date.strftime("%d %B %Y") %> - <%= booking.end_date.strftime("%d %B %Y") %></p>
            <%= link_to "Edit booking", edit_booking_path(booking), class: "button-blue review-button text-center" %>
            <%= link_to "Delete booking", booking_path(booking), data: { turbo_method: :delete,
            turbo_confirm: "Are you sure you want to delete your booking?" }, class: "button-blue review-button text-center" %>
          </div>
        </div>
      </div>
    <% end %>

  <h2 class="booking-header">Previous bookings</h2>
  <% @past_bookings.each do |booking| %>
    <% venue = booking.venue %>
    <div class="row my-3">
      <div class="card">
      <%= link_to venue_path(venue) do %>
          <% if booking.venue.photo.attached? %>
            <%= cl_image_tag(booking.venue.photo.key, crop: :thumb, gravity: :face, radius: 5) %>
          <% else %>
            <%= image_tag(booking.venue.pic_url, crop: :thumb, gravity: :face, radius: 5) %>
          <% end %>
        <% end %>
        <div class="card-body d-flex flex-column">
          <h5 class="card-title"><strong><%= link_to venue.name, booking_path(booking), class: "text-dark" %></strong></h5>
          <p class="card-text card-location"><%= venue.location %></p>
          <p class="card-text text-muted"><strong>Booking completed on:</strong> <%= booking.end_date.strftime("%d %B %Y") %></p>
          <%= link_to "Leave a review", booking_path(booking, anchor: "review"), class: "button-blue review-button text-center"%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>