config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "venues#index"
  get "profile", to: "pages#profile", as: :profile

  resources :venues do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[create]
  end

  resources :reviews, only: %i[destroy]
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, :location, presence: true
  validates :price_per_day, :size_of_band, presence: true, numericality: { only_integer: true }
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:start].present? && params[:end].present?
      @venues = []
      compare_dates((params[:start].to_date..params[:end].to_date).to_a)
      @venues
    else
      @venues = Venue.all
    end
    set_markers
    # session[:search_start] = params[:start]
    # session[:search_end] = params[:end]
  end

  def show
    @review = Review.new
    @marker = []
    set_markers
    @marker << @markers.find { |m| m[:lat] == @venue.latitude && m[:lng] == @venue.longitude }
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.create(venue_params)
    @venue.user = current_user
    if @venue.save!
      redirect_to venue_path(@venue), notice: "A new venue was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @venue.update(venue_params)
      redirect_to venue_path(@venue)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @venue.destroy
    redirect_to profile_path, notice: 'Venue deleted'
  end

  private

  def set_markers
    @venues = Venue.all
    @markers = @venues.geocoded.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window_html: render_to_string(partial: "popup", locals: { venue: }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def set_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:name, :price_per_day, :location, :size_of_band, :description, :phone_number, :photo)
  end

  def compare_dates(date_range)
    Venue.all.each do |venue|
      available = true
      venue.bookings.each do |booking|
        available = false if (booking.start_date..booking.end_date).to_a.intersect?(date_range)
      end
      @venues << venue if available
    end
  end
end

app/views/venues/_form.html.erb
<div class="container">
  <%= form_with model: @venue do |f| %>
    <div class="col-2 mt-2">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
      <%= f.label :price_per_day, "Price per day", class: "mt-4" %>
      <%= f.number_field :price_per_day %>
      <div data-controller="location-autocomplete", data-location-autocomplete-api-key-value="<%= ENV.fetch('MAPBOX_API_KEY') %>">
        <%= f.label :location, "Location", class: "mt-4" %>
        <%= f.text_field :location, data: { location_autocomplete_target: "location" } %>
      </div>
      <%= f.label :size_of_band, "Size of band", class: "mt-4" %>
      <%= f.number_field :size_of_band %>
      <%= f.label :name, "Description", class: "mt-4" %>
      <%= f.text_area :description %>
      <%= f.label :phone_number, "Phone number", class: "mt-4" %>
      <%= f.text_field :phone_number %>
      <%= f.label :photo, "Photo of venue", class: "mt-4" %>
      <%= f.file_field :photo, as: :file %>
      <!-- f.input :photos, as: :file, input_html: { multiple: true } -->
      <%= f.submit "Add venue", class: "mt-4" %>
    </div>
  <% end %>
</div>

    <%# <%= f.error_notification %>
    <%# <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <!-- fs to group: not sure where these came from or what they mean - let's discuss! -->

app/views/venues/_marker.html.erb
<%= image_tag "guitar.png", height: 30, width: 30, alt: "Guitar" %>

app/views/venues/_popup.html.erb
<div class="popup">
  <h5><%= venue.name %></h5>
  <p><%= venue.location %></p>
  <p>
    <i class="fa-solid fa-users me-1"></i><%= venue.size_of_band %> |
    <i class="fa-solid fa-tag me-1 ms-1"></i>£<%= venue.price_per_day %> |
    <%= venue.reviews.present? ? "#{average_rating(venue.reviews)}⭐" : "No ratings" %>
  </p>
  <%= link_to "Venue details", venue_path(venue), id: "popup-button" %>
  </div>

app/views/venues/edit.html.erb
<div class="container">
<h1 class="mt-2">Edit venue</h1>
  <div class="col-2 mt-2">
    <%= form_with model: @venue do |f| %>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
      <%= f.label :price_per_day, "Price per day", class: "mt-4" %>
      <%= f.number_field :price_per_day %>
      <%= f.label :location, "Location", class: "mt-4" %>
      <%= f.text_field :location %>
      <%= f.label :size_of_band, "Size of band", class: "mt-4" %>
      <%= f.number_field :size_of_band %>
      <%= f.label :name, "Description", class: "mt-4" %>
      <%= f.text_area :description %>
      <%= f.label :phone_number, "Phone number", class: "mt-4" %>
      <%= f.text_field :phone_number %>
      <%= f.label :photo, "Photo of venue", class: "mt-4" %>
      <%= f.file_field :photo, as: :file %>
      <%= f.submit "Update venue", class: "mt-4" %>
    <% end %>
  </div>
</div>

app/views/venues/index.html.erb
<div class="container">
  <div class="row">
    <form>
      <label for="start" class="mt-2"><b>Start date</b></label>
      <div class="col-2">
        <input class="form-control my-2" id="start" name="start" type="date">
      </div>
      <label for="end"><b>End date</b></label>
      <div class="col-2">
        <input class="form-control my-2" id="end" name="end" type="date">
      </div>
      <button class="btn btn-success mt-2" type="submit">Search</button>
    </form>
  </div>
  <div id="map" data-controller="map" data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <div class="row d-flex justify-content-center">
    <% @venues.each do |venue| %>
      <div class="venue-card">
        <%= link_to venue_path(venue) do %>
          <% if venue.photo.attached? %>
            <%= cl_image_tag(venue.photo.key) %>
          <% elsif venue.pic_url?%>
            <%= image_tag(venue.pic_url) %>
          <% else %>
            <%= cl_image_tag("n91dnimxrk7oac5lykmw") %>
          <% end %>
        <% end %>
        <div class="venue-card-infos">
          <div>
            <h2><%= link_to venue.name, venue_path(venue.id) %></h2>
            <p><%= venue.location %></p>
            <p id="text-bottom">
              <i id="people-icon" class="fa-solid fa-users"></i> <%= venue.size_of_band %> people |
              <i id="price-icon" class="fa-solid fa-tag"></i>£<%= venue.price_per_day %> |
              <%= venue.reviews.present? ? "#{average_rating(venue.reviews)}⭐" : "No ratings" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

  <%# <form class="d-flex justify-content-center mt-4">
    <div class="row">
      <div class="col-4">
        <div class="mt-4">
          <label for="start" class=""><strong>Start date</strong></label>
          <input class="form-control my-2" id="start" name="start" type="date">
        </div>
        <div class="mt-4">
          <label for="end"><strong>End date</strong></label>
          <input class="form-control my-2" id="end" name="end" type="date">
        </div>
      </div>
      <div class="col-4">
        <div class="mt-4">
          <label for="min-price"><strong>Min price</strong></label>
          <input class="form-control my-2" id="min-price" name="minprice" type="text">
        </div>
        <div class="mt-4">
          <label for="max-price"><strong>Max price</strong></label>
          <input class="form-control my-2" id="max-price" name="maxprice" type="text">
        </div>
      </div>
      <div class="col-4">
        <div class="mt-4">
          <label for="min-members"><strong>Min band members</strong></label>
          <input class="form-control my-2" id="min-members" name="minmembers" type="text">
        </div>
        <div class="mt-4">
          <label for="max-members"><strong>Max band members</strong></label>
          <input class="form-control my-2" id="max-members" name="maxmembers" type="text">
        </div>
      </div>
        <div class="my-3">
          <button class="button-blue" type="submit">Search</button>
        </div>
    </div>
  </form> %>

app/views/venues/new.html.erb
<div class="container mb-5">
  <h2 class="my-3">Create your venue</h2>
  <%= render "form", venue: @venue %>
</div>

app/views/venues/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
    <h1 id="show-header" class="mt-5 mb-4"><%= @venue.name %></h1>
    <div class="mt-3 ms-1 mb-4">
      <% if @venue.photo.attached? %>
        <%= cl_image_tag(@venue.photo.key, width: 287, height: 150, crop: :thumb, gravity: :face, radius: 5) %>
      <% else %>
        <%= image_tag(@venue.pic_url, width: 287, height: 150, crop: :thumb, gravity: :face, radius: 5) %>
      <% end %>
    </div>
    <p><i class="fa-solid fa-tag me-3"></i> £<%= @venue.price_per_day %> per day</p>
    <p><i class="fa-solid fa-location-dot me-3"></i> <%= @venue.location%></p>
    <p><i class="fa-solid fa-users me-2"></i> Up to <%= @venue.size_of_band %></i></p>
    <p><i class="fa-solid fa-circle-info me-3"></i><%= @venue.description %></p>
    <p><i class="fa-solid fa-wheelchair me-3"></i>Wheelchair accessible</p>
    <div class="mt-5">
      <%= link_to "Back to all venues", root_path, class: "button-blue" %>
      <%= link_to "Book venue", new_venue_booking_path(@venue), class: "button-blue" %>
    </div>
    <% if @venue.user == current_user %>
      <button class="btn btn-warning mt-2" type="submit">
        <%= link_to "Edit venue", edit_venue_path(@venue), class: "text-white" %>
      </button>
    <% end %>
    <% if @venue.user == current_user %>
      <%= link_to "Delete venue", venue_path(@venue), data: { turbo_method: :delete,
        turbo_confirm: "Are you sure you want to delete your venue?" }, class: "button-blue" %>
    <% end %>
    </div>
    <div class="col-6" id="show-map">
    <div class="mt-5" id="map" style="width: 90%; height: 300px; margin-top: 50px;"
      data-controller="map"
      data-map-markers-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    </div>
    <h3 class="mt-5 mb-4">Reviews</h3>
    <% if @venue.reviews.present? %>
      <% @venue.reviews.each do |review| %>
        <div class="d-flex">
          <% x = review.rating %>
            <% x.times do %>
              <p>⭐</p>
            <% end %>
        </div>
        <p><%= review.comment %></p>
        <p><% if current_user == review.booking.user %>
          <%= link_to "Delete review", review_path(review), data: { turbo_method: :delete,
          turbo_confirm: "Are you sure you want to delete your review?" } %></p>
        <% end %>
        <hr>
      <% end %>
    <% else %>
    <p>There are currently no reviews for this venue.</p>
  <% end %>
</div>
</div>